name: deps_relay
description: A simple mobile Hosted Pub Repository Specification Version 2 relay/cache server that supports local / hosted and git upstreams.
version: 0.0.1
repository: https://github.com/mikklfr/deps_relay

environment:
  sdk: ^3.3.4

dependencies:
  alfred: ^1.1.1
  args: ^2.5.0
  async: ^2.11.0
  aws_s3_api: ^2.0.0
  copy_with_extension: ^5.0.4
  crypto: ^3.0.3
  get_it: ^7.7.0
  git: ^2.2.1
  git_clone: ^1.2.0
  hive: ^2.2.3
  hive_generator: ^2.0.1
  http: ^1.2.1
#  isar: 3.1.0+1
  isar:
    git:
      url: https://github.com/mikklfr/isar.git
      ref: linux/3.1.0+1
      path: packages/isar
  json_annotation: ^4.9.0
  path: ^1.9.0
  rw_git: ^1.0.3
  synchronized: ^3.1.0+1
  tar: ^1.0.5
  tmp_path: ^1.3.1
  ttl_cache: ^0.3.0
  uuid: ^4.4.0
  yaml: ^3.1.2
  yaml_writer: ^2.0.0

dev_dependencies:
  build_runner: 2.4.9
  json_serializable: ^6.8.0
  lints: 3.0.0
  test: 1.24.0
#  isar_generator: ^3.1.0+1
  isar_generator:
    git:
      url: https://github.com/mikklfr/isar.git
      ref: linux/3.1.0+1
      path: packages/isar_generator
  copy_with_extension_gen: ^5.0.4

dependency_overrides:
  shared_aws_api:
    git:
      url: https://github.com/mikklfr/aws_client.git
      ref: fix/signature
      path: shared_aws_api
  isar:
    git:
      url: https://github.com/mikklfr/isar.git
      ref: linux/3.1.0+1
      path: packages/isar
  isar_generator:
    git:
      url: https://github.com/mikklfr/isar.git
      ref: linux/3.1.0+1
      path: packages/isar_generator